CREATE TABLE IF NOT EXISTS "User"
(
    id                BIGINT NOT NULL UNIQUE,
    name              VARCHAR(255),
    stage             INTEGER,
    isCreationRequest BOOLEAN,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE Request
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT,
    specAge       VARCHAR(255),
    gender        VARCHAR(255),
    methodTherapy VARCHAR(255),
    clientAge     VARCHAR(255),
    clientGender  VARCHAR(255),
    diagnosis     VARCHAR(255),
    clientRequest VARCHAR(255),
    budget        VARCHAR(255),
    extra         VARCHAR(255),
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT FK_REQUEST_ON_USER FOREIGN KEY (user_id) REFERENCES "User" (id)
);

CREATE TABLE User_requests
(
    User_id     BIGINT NOT NULL,
    requests_id BIGINT NOT NULL,
    CONSTRAINT fk_usereq_on_request FOREIGN KEY (requests_id) REFERENCES Request (id),
    CONSTRAINT fk_usereq_on_user FOREIGN KEY (User_id) REFERENCES "User" (id)
);

ALTER TABLE User_requests
    ADD CONSTRAINT fk_usereq_on_request FOREIGN KEY (requests_id) REFERENCES Request (id);

ALTER TABLE User_requests
    ADD CONSTRAINT fk_usereq_on_user FOREIGN KEY (User_id) REFERENCES "User" (id);