/*CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT NOT NULL UNIQUE,
    name              VARCHAR(255),
    stage             INTEGER,
    isCreationRequest BOOLEAN,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS request
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT,
    spec_age       VARCHAR(255),
    gender        VARCHAR(255),
    method_therapy VARCHAR(255),
    client_age     VARCHAR(255),
    client_gender  VARCHAR(255),
    diagnosis     VARCHAR(255),
    client_request VARCHAR(255),
    budget        VARCHAR(255),
    extra         VARCHAR(255),
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT FK_REQUEST_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS user_requests
(
    User_id     BIGINT NOT NULL,
    requests_id BIGINT NOT NULL,
    CONSTRAINT fk_usereq_on_request FOREIGN KEY (requests_id) REFERENCES Request (id),
    CONSTRAINT fk_usereq_on_user FOREIGN KEY (User_id) REFERENCES users (id)
);
*/